### ISSUE TITLE
Failures of end-to-end tests on K8s 1.16|1.17

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#243]
**Describe the bug**

Extensive (sorry!) testing of the end-to-end tests for the Webhook for Configurations uncovered issues with the existing end-to-end tests on the following Kubernetes distro-versions.

This bug identifies and tracks their resolution.

|Distro|Version|Failure|Link|
|--------|:-----:|-------|----|
|K3s|1.16|Akri not running in expected state|[1889124406](https://github.com/deislabs/akri/runs/1889124406?check_suite_focus=true)|
|MicroK8s|1.16|Nothing to do for helm3|[1882806752](https://github.com/deislabs/akri/runs/1882806752?check_suite_focus=true)|
|MicroK8s|1.17|Nothing to do for helm3|[1882806782](https://github.com/deislabs/akri/runs/1882806782?check_suite_focus=true)|

> **NOTE** The above links are non-exhaustive and assumed (!) to be consistent

**To Reproduce**

Run GitHub Actions workflow: Test K3s, Kubernetes, and MicroK8s

**Expected behavior**

Success

**Comment by DazWilkin** [comment]
Distro: K3s
Version: v1.16.14+k3s1

See: https://github.com/deislabs/akri/pull/206#issuecomment-778347929

`run-end-to-end.py` during "Check that slot reconciliation is working on agent"

```console
Check logs for Agent slot-reconciliation for pod akri-agent-daemonset-v26qg
Successfully stored Agent logs in /tmp/agent_log.txt
Akri failed to successfully connect to crictl via the CRI socket with return value of {} CompletedProcess(args=['grep', 'get_node_slots - crictl called successfully', '/tmp/agent_log.txt'], returncode=1)
NAME                                              READY   STATUS    RESTARTS   AGE    LABELS
pod/akri-agent-daemonset-v26qg                    1/1     Running   0          2m3s   controller-revision-hash=55c59797f8,name=akri-agent,pod-template-generation=1
pod/akri-controller-deployment-6d87f94d7f-68527   1/1     Running   0          2m3s   app=akri-controller,pod-template-hash=6d87f94d7f
pod/akri-debug-echo-foo-b1f919-pod                1/1     Running   0          21s    akri.sh/configuration=akri-debug-echo-foo,akri.sh/instance=akri-debug-echo-foo-b1f919,akri.sh/target-node=k3s,app=akri-debug-echo-foo-b1f919-pod,controller=akri.sh
pod/akri-debug-echo-foo-a6bfcc-pod                1/1     Running   0          21s    akri.sh/configuration=akri-debug-echo-foo,akri.sh/instance=akri-debug-echo-foo-a6bfcc,akri.sh/target-node=k3s,app=akri-debug-echo-foo-a6bfcc-pod,controller=akri.sh

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE    LABELS
service/kubernetes                       ClusterIP   10.43.0.1       <none>        443/TCP    3h4m   component=apiserver,provider=kubernetes
service/akri-debug-echo-foo-b1f919-svc   ClusterIP   10.43.29.0      <none>        6052/TCP   16s    akri.sh/instance=akri-debug-echo-foo-b1f919,app=akri-debug-echo-foo-b1f919-svc,controller=akri.sh
service/akri-debug-echo-foo-svc          ClusterIP   10.43.123.141   <none>        6052/TCP   16s    akri.sh/configuration=akri-debug-echo-foo,app=akri-debug-echo-foo-svc,controller=akri.sh
service/akri-debug-echo-foo-a6bfcc-svc   ClusterIP   10.43.191.49    <none>        6052/TCP   16s    akri.sh/instance=akri-debug-echo-foo-a6bfcc,app=akri-debug-echo-foo-a6bfcc-svc,controller=akri.sh

NAME                                        CAPACITY   AGE    LABELS
configuration.akri.sh/akri-debug-echo-foo   1          2m3s   app.kubernetes.io/managed-by=Helm

NAME                                          CONFIG                SHARED   NODES     AGE   LABELS
instance.akri.sh/akri-debug-echo-foo-b1f919   akri-debug-echo-foo   false    ["k3s"]   21s   <none>
instance.akri.sh/akri-debug-echo-foo-a6bfcc   akri-debug-echo-foo   false    ["k3s"]   21s   <none>
[2021-02-12T19:56:30Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:56:30Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:56:40Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:56:40Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:56:50Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:56:50Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:00Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:00Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:10Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:10Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:20Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:20Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:30Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:30Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:40Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:40Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:50Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:57:50Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:00Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:00Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:10Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:10Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:21Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T19:58:21Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/dazwilkin/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/dazwilkin/.kube/config
release "akri" uninstalled
Traceback (most recent call last):
  File "./test/run-end-to-end.py", line 190, in <module>
    main()
  File "./test/run-end-to-end.py", line 69, in main
    raise RuntimeError("Scenario Failed")
RuntimeError: Scenario Failed
````

I'm unfamiliar with K3s but:

```bash
k3s crictl
FATA[2021-02-12T20:16:35.904155143Z] load config file: stat /var/lib/rancher/k3s/data/8f4b194129852507eab4a55117fc942e0688ec9a70ffdaa5911ccc6652220f76/bin/crictl.yaml: no such file or directory 
```
But:
```bash
sudo find / -name crictl.yaml
/var/lib/rancher/k3s/agent/etc/crictl.yaml

sudo more /var/lib/rancher/k3s/agent/etc/crictl.yaml
runtime-endpoint: unix:///run/k3s/containerd/containerd.sock
```
Curiously:
```
crictl --runtime-endpoint=unix:///run/k3s/containerd/containerd.sock
FATA[2021-02-12T20:19:17.251521280Z] load config file: stat /var/lib/rancher/k3s/data/8f4b194129852507eab4a55117fc942e0688ec9a70ffdaa5911ccc6652220f76/bin/crictl.yaml: no such file or directory 
```
But:

```bash
sudo crictl --config=/var/lib/rancher/k3s/agent/etc/crictl.yaml images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/curlimages/curl                  latest              26a9afb7027cc       3.99MB
docker.io/library/nginx                    latest              298ec0e28760b       53.6MB
docker.io/rancher/coredns-coredns          1.8.0               296a6d5035e2d       12.9MB
docker.io/rancher/klipper-helm             v0.4.3              3b0b04aa3473f       50.7MB
docker.io/rancher/klipper-lb               v0.1.2              897ce3c5fc8ff       2.71MB
docker.io/rancher/library-traefik          1.7.19              aa764f7db3051       24MB
docker.io/rancher/local-path-provisioner   v0.0.14             e422121c9c5f9       13.4MB
docker.io/rancher/metrics-server           v0.3.6              9dd718864ce61       10.5MB
docker.io/rancher/pause                    3.1                 da86e6ba6ca19       327kB
ghcr.io/dazwilkin/agent                    v0.2.0-amd64        37c6c1341d91e       55.1MB
ghcr.io/dazwilkin/controller               v0.2.0-amd64        922d63d713bdd       52.8MB
ghcr.io/dazwilkin/webhook-configuration    v0.2.0-amd64        c1eb9ea9d4ca9       50.1MB
```

**Comment by DazWilkin** [comment]
Distro: MicroK8s
Version: v1.16 & v1.16

Error: "Nothing to do for helm3"

Hypothesis: MicroK8s 1.16|1.17 **didn't** include helm3 ;-)

**Comment by bfjelds** [comment]
i wonder if the k3s 1.16 failure isn't because crictl 1.17 is being installed and used by akri.

**Comment by DazWilkin** [comment]
> Distro: MicroK8s
> Version: v1.16 & v1.16
> 
> Error: "Nothing to do for helm3"
> 
> Hypothesis: MicroK8s 1.16|1.17 **didn't** include helm3 ;-)

Confirmed:

```
sudo snap install microk8s --classic --channel=1.16/stable
microk8s (1.16/stable) v1.16.15 from Canonical✓ installed

sudo microk8s status --wait-ready
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: disabled
fluentd: disabled
gpu: disabled
helm: disabled
ingress: disabled
istio: disabled
jaeger: disabled
knative: disabled
linkerd: disabled
metrics-server: disabled
prometheus: disabled
rbac: disabled
registry: disabled
storage: disabled
```

And:

MicroK8s 1.18 - 26 March 2020
New Helm 3 addon, available with microk8s helm3, thanks @qs
https://microk8s.io/docs/release-notes

Confused: I don't know how Helm is being installed for these images .... ?

I think `sudo microk8s.enable helm3` is a red-herring as it's not aliased in the test script and appears unused.

When I created VMs running these distros I had to install Helm manually but I'm unable to find it in the scripts.

**Comment by DazWilkin** [comment]
> i wonder if the k3s 1.16 failure isn't because crictl 1.17 is being installed and used by akri.
> 
> maybe changing to the crictl installation step to this would fix it:
> 
> ```shell
>         VERSION="v1.16.0"
>         curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz
>         sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C $(pwd)
>         rm -f crictl-$VERSION-linux-amd64.tar.gz
> ```

Presumably this is an (as yet undiscovered) issues with MicroK8s 1.16 (1.17) too as it installs `crictl` too?

Should we expand the `matrix` to include `crictl` `VERSION`?

**Comment by bfjelds** [comment]
> Should we expand the matrix to include crictl VERSION?

Makes sense to me.

**Comment by DazWilkin** [comment]
Added: `crictl: v1.16.0`

And revised (removing `VERSION=....` as it was there solely to set the variable for these steps):

```bash
curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/${{ matrix.kube.crictl }}/crictl-${{ matrix.kube.crictl }}-linux-amd64.tar.gz --output crictl-${{ matrix.kube.crictl }}-linux-amd64.tar.gz
sudo tar zxvf crictl-${{ matrix.kube.crictl }}-linux-amd64.tar.gz -C /usr/local/bin
rm -f crictl-${{ matrix.kube.crictl }}-linux-amd64.tar.gz
echo '--set agent.host.crictl=/usr/local/bin/crictl --set agent.host.dockerShimSock=/var/snap/microk8s/common/run/containerd.sock' > /tmp/cri_args_to_test.txt
```

Because this step is duplicated for K3s and MicroK8s, it may be cleaner to refactor this into its own step predicated on those distros.

**Comment by DazWilkin** [comment]
It would be good to confirm whether Kubernetes and `crictl` are version-sync'd (https://github.com/deislabs/akri/issues/245)

**Comment by bfjelds** [comment]
> It would be good to confirm whether Kubernetes and `crictl` are version-sync'd (#245)

agreed.  i've seen 1.17 working with several versions and don't specifically know that this is the cause of k3s 1.16 failing.  :)

**Comment by DazWilkin** [comment]
> > It would be good to confirm whether Kubernetes and `crictl` are version-sync'd (#245)
> 
> agreed. i've seen 1.17 working with several versions and don't specifically know that this is the cause of k3s 1.16 failing. :)

Let's find out: https://github.com/deislabs/akri/runs/1890607388?check_suite_focus=true

**Comment by DazWilkin** [comment]
K3s 1.17 is my fault .... typo in `matrix`.

**Comment by DazWilkin** [comment]
Distro: K3s
Version:

Slightly different error when using `crictl` 1.16.0.


```console
Successfully stored Agent logs in /tmp/agent_log.txt
Akri failed to successfully connect to crictl via the CRI socket with return value of {} CompletedProcess(args=['grep', 'get_node_slots - crictl called successfully', '/tmp/agent_log.txt'], returncode=1)
NAME                                              READY   STATUS    RESTARTS   AGE     LABELS
pod/akri-controller-deployment-6d87f94d7f-wr59d   1/1     Running   0          2m47s   app=akri-controller,pod-template-hash=6d87f94d7f
pod/akri-agent-daemonset-xvbk2                    1/1     Running   3          2m47s   controller-revision-hash=55c59797f8,name=akri-agent,pod-template-generation=1
pod/akri-debug-echo-foo-a6bfcc-pod                1/1     Running   0          22s     akri.sh/configuration=akri-debug-echo-foo,akri.sh/instance=akri-debug-echo-foo-a6bfcc,akri.sh/target-node=k3s,app=akri-debug-echo-foo-a6bfcc-pod,controller=akri.sh
pod/akri-debug-echo-foo-b1f919-pod                1/1     Running   0          22s     akri.sh/configuration=akri-debug-echo-foo,akri.sh/instance=akri-debug-echo-foo-b1f919,akri.sh/target-node=k3s,app=akri-debug-echo-foo-b1f919-pod,controller=akri.sh

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE     LABELS
service/kubernetes                       ClusterIP   10.43.0.1       <none>        443/TCP    5h43m   component=apiserver,provider=kubernetes
service/akri-debug-echo-foo-a6bfcc-svc   ClusterIP   10.43.208.50    <none>        6052/TCP   15s     akri.sh/instance=akri-debug-echo-foo-a6bfcc,app=akri-debug-echo-foo-a6bfcc-svc,controller=akri.sh
service/akri-debug-echo-foo-svc          ClusterIP   10.43.47.234    <none>        6052/TCP   15s     akri.sh/configuration=akri-debug-echo-foo,app=akri-debug-echo-foo-svc,controller=akri.sh
service/akri-debug-echo-foo-b1f919-svc   ClusterIP   10.43.243.228   <none>        6052/TCP   15s     akri.sh/instance=akri-debug-echo-foo-b1f919,app=akri-debug-echo-foo-b1f919-svc,controller=akri.sh

NAME                                        CAPACITY   AGE     LABELS
configuration.akri.sh/akri-debug-echo-foo   1          2m47s   app.kubernetes.io/managed-by=Helm

NAME                                          CONFIG                SHARED   NODES     AGE   LABELS
instance.akri.sh/akri-debug-echo-foo-b1f919   akri-debug-echo-foo   false    ["k3s"]   22s   <none>
instance.akri.sh/akri-debug-echo-foo-a6bfcc   akri-debug-echo-foo   false    ["k3s"]   22s   <none>
[2021-02-12T22:35:07Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:07Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:17Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:17Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:27Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:27Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:37Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:37Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:47Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:47Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:57Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:35:57Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:07Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:07Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:17Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:17Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:27Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:27Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:37Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:37Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:47Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:47Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:57Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2021-02-12T22:36:57Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
WARN[2021-02-12T22:36:59.791527246Z] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
WARN[2021-02-12T22:37:00.107726535Z] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/dazwilkin/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/dazwilkin/.kube/config
release "akri" uninstalled
Traceback (most recent call last):
  File "./test/run-end-to-end.py", line 191, in <module>
    main()
  File "./test/run-end-to-end.py", line 69, in main
    raise RuntimeError("Scenario Failed")
RuntimeError: Scenario Failed
```

But:

```console
more /tmp/cri_args_to_test.txt 
--set agent.host.crictl=$(pwd)/crictl --set agent.host.dockerShimSock=/run/k3s/containerd/containerd.sock
```

Which looks incorrect.

Tried (quotes and `${PWD}`):

```console
echo "--set agent.host.crictl=${PWD}/crictl --set agent.host.dockerShimSock=/run/k3s/containerd/containerd.sock" > /tmp/cri_args_to_test.txt
```
And (success):

```console
Check logs for Agent slot-reconciliation for pod akri-agent-daemonset-tf5w9
Press enter to continue.

Successfully stored Agent logs in /tmp/agent_log.txt
[2021-02-12T22:42:00Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:42:10Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:42:20Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:42:30Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:42:40Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:42:50Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:43:00Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:43:10Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:43:20Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
[2021-02-12T22:43:30Z TRACE agent::util::slot_reconciliation] get_node_slots - crictl called successfully
Getting pod name [akri.sh/configuration=akri-debug-echo-foo]
Deleting broker pod: sudo kubectl delete pod akri-debug-echo-foo-a6bfcc-pod
pod "akri-debug-echo-foo-a6bfcc-pod" deleted
```

**Comment by bfjelds** [comment]
> Tried (quotes and ${PWD})

Kind of amazing that it ever worked ... nice find!!!

**Comment by DazWilkin** [comment]
On the hoof: Right! I'm hoping it's not a red-herring. Will revise the job Monday (assuming we don't lose power in tonight's storm) and confirm then

**Comment by bfjelds** [comment]
I hope it doesn't step on your toes, but I had a few minutes so updated your branch with the matrix fix and the pwd fix.  It'll help me sleep at night to know if you've gotten akri to work on so many new versions :)

**Comment by bfjelds** [comment]
> I hope it doesn't step on your toes, but I had a few minutes so updated your branch with the matrix fix and the pwd fix. It'll help me sleep at night to know if you've gotten akri to work on so many new versions :)

I still see the error on k3s 1.16.  Perhaps the original crictl path with `$(pwd)` gets substituted when the `helm install` command gets run maybe?  In any case, I can repro the problem in a local VM using K3s 1.16.

**Comment by bfjelds** [comment]
maybe k3s 1.16 doesn't support device-plugin.  when i search for the /var/lib/kubelet/device-plugins/kubelet.sock, it isn't there.

this seems related: https://github.com/k3s-io/k3s/issues/1390

if i create this link `ln -s /var/lib/rancher/k3s/agent/kubelet/device-plugins/ /var/lib/kubelet/device-plugins`, instances and brokers are created.

**Comment by DazWilkin** [comment]
You'd never step on my toes. Thanks for the thoughtfulness and for making the change.

Aha!

**Comment by DazWilkin** [comment]
> > I hope it doesn't step on your toes, but I had a few minutes so updated your branch with the matrix fix and the pwd fix. It'll help me sleep at night to know if you've gotten akri to work on so many new versions :)
> 
> I still see the error on k3s 1.16. Perhaps the original crictl path with `$(pwd)` gets substituted when the `helm install` command gets run maybe? In any case, I can repro the problem in a local VM using K3s 1.16.

When is `helm install` run? I don't understand where `helm` is added to these VMs.

**Comment by bfjelds** [comment]
> When is helm install run? I don't understand where helm is added to these VMs.

you are correct that helm is not in the VMs.  i was suspecting that the `$(pwd)` string gets added to `/tmp/cri_args_to_test.txt` ... that file is read into the python variable `cri_args` and then added to `helm_install_command`, which is then executed in a shell command.  i was speculating that when `helm_install_command` is executed, `$(pwd)` is evaluated and replaced. (and we luck out that the python test is executing with the same working directory as the workflow yaml)

**Comment by DazWilkin** [comment]
> > When is helm install run? I don't understand where helm is added to these VMs.
> 
> you are correct that helm is not in the VMs. i was suspecting that the `$(pwd)` string gets added to `/tmp/cri_args_to_test.txt` ... that file is read into the python variable `cri_args` and then added to `helm_install_command`, which is then executed in a shell command. i was speculating that when `helm_install_command` is executed, `$(pwd)` is evaluated and replaced. (and we luck out that the python test is executing with the same working directory as the workflow yaml)

I apologize.... My comment was poorly written. I meant "When is Helm installed?" not (what I wrote) "When is `helm install` run?"

I don't understand how Helm is available to the tests. [I also don't understand where Python 3.7 is installed]

Creating VMs to run the tests manually, I had to install Helm on each. When I realized that the MicroK8s `sudo microk8s.enable helm3` command is ineffectual, I tried to find where Helm was added in the workflow because it's there for the MicroK8s  tests. 

I'm unable to determine where Helm is installed and yet it's available in the workflow for each distro.

**Comment by bfjelds** [comment]
> I don't understand how Helm is available to the tests.

Heh ... I just looked and don't understand it either.  Maybe it is included in the container or with this:

```yaml
    - name: Install Python kubernetes dependency
      run: |
        python -m pip install --upgrade pip
        pip install kubernetes
```


Python is installed here, but i'm not sure where 3.7 would come from:

```yaml
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
       python-version: 3.8 
```

**Comment by DazWilkin** [comment]
Doh.... Yes, to Python 3.8 (was looking for 3.7 :smile: ), apologies! OK, that's resolved.

But Helm!?

**Comment by bfjelds** [comment]
> But Helm!?

Helm is a part of the `runs-on: ubuntu-18.04` container.  I just verified with a separate workflow.

**Comment by DazWilkin** [comment]
> > But Helm!?
> 
> Helm is a part of the `runs-on: ubuntu-18.04` container. I just verified with a separate workflow.
> 
> `helm version`
> 
> ```
> version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
> ```
> 
> kubectl is a part of the container too ... `kubectl version`
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5797eaecac19b9c0e4d10d3d6b559c074e3c3c88", GitTreeState:"clean", BuildDate:"2021-01-27T07:28:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
> ```

Thank you!!
